import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import FirstSection from '@/components/first-section'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className='d-flex justify-content-center py-2'>
          <div className='col-11'>
            <Navbar />
            <FirstSection />
            <div className='w-100' style={{ backgroundColor: "red", height: "5rem" }}>

            </div>
          </div>
        </div>
      </div>
    </>
  )
}
