import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/navbar";
import FirstSection from "@/components/first-section";
import MyTechSection from "@/components/tech-sec";
import MyProjectSection from "@/components/my-project-section";
import Footer from "@/components/footer";
import Layout from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <FirstSection />
        <MyTechSection />
        <MyProjectSection />
      </Layout>
    </>
  );
}
